### ISSUE TITLE
Section header animations

### ISSUE THREAD

**Issue by ho87** [ho87/immobilienbewertung#44]
📝 Description
Apply a pulsating animation to section headers when a section is partially filled (at least one field touched but not all complete), and remove the animation once the section is fully completed.

🎯 Goal:
Provide users with a visual cue that a section still needs attention by pulsating its header until all its fields are valid, then stopping the animation.

⚙️ Acceptance Criteria
1. **Target Elements:** The following headers must support pulsation:  
   - `#site-header` (Immobilienbewertung)  
   - `#header-inseratsdaten` (Inseratsdaten)  
   - `#header-immobiliendaten` (Immobiliendaten)  
   - `#header-finanzierung` (Finanzierung)  
   - `#header-gebaeude` (Gebäudezustand)  

2. **Trigger Logic:**  
   - On any `input` or `change` within a section’s fields:  
     - **If** ≥1 field has a non-empty/valid value AND <100% of that section’s fields are complete → add CSS class `pulsate` to the section header.  
     - **If** 100% of that section’s fields are complete → remove `pulsate` class.  
     - **If** 0 fields are touched → ensure no `pulsate` class is present.

3. **Animation Definition:**  
   - Define a CSS keyframes animation named `pulse`:  
     ```css
     @keyframes pulse {
       0%   { transform: scale(1); }
       50%  { transform: scale(1.05); }
       100% { transform: scale(1); }
     }
     .pulsate {
       animation: pulse 1.5s ease-in-out infinite;
     }
     ```  

4. **Dynamic Class Management:**  
   - Use JavaScript to add/remove `.pulsate` on the header element based on the section’s completion state.  
   - Ensure event listeners are efficient (debounced if necessary) to avoid performance lag.

5. **Responsive & Accessibility:**  
   - The pulsation must be smooth on both desktop and mobile.  
   - Provide an `aria-live="polite"` region marking to announce “Section [Name] incomplete” when pulsation starts, and “Section [Name] complete” when it stops.
